name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  cargo-publish:
    name: Publish crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo publish
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
