name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4

    - name: Format
      run: |
        rustup component add rustfmt
        cargo fmt --check --verbose

    - name: Build
      run: cargo build --verbose

    - name: Tests
      run: cargo test --verbose -- --show-output

    - name: Docs
      run: cargo doc --verbose

  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check typos
        uses: crate-ci/typos@master
