name: CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Format
      run: |
        rustup component add rustfmt
        cargo fmt --check --verbose

    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy

    - name: Build
      run: cargo build --verbose

    - name: Cache folder
      run: |
        pwd
        ls
        ls /home/runner/
        mkdir /home/runner/.cache/

    - name: Tests
      run: cargo test cache --verbose -- --show-output
      #run: cargo test --all --verbose


